# Triton Server Configurations
triton_launch_mode: docker
triton_docker_image: nvcr.io/nvidia/tritonserver:24.06-py3
triton_grpc_endpoint: localhost:8001  # Update if using a different endpoint
model_repository: /workspace/model_repository

# Output paths
output_model_repository_path: /workspace/output

# Profiling parameters
profile_models:
  - densenet_onnx



# GPU Configurations
gpus:
  - all