services:
  triton-server:
    container_name: triton-server
    image: nvcr.io/nvidia/tritonserver:24.06-py3
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    shm_size: 256m
    command: tritonserver --model-repository=/models --model-control-mode=explicit --load-model=*
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    volumes:
      - ../model_repository:/models
      - ../:/workspace/
    environment:
      - NVIDIA_VISIBLE_DEVICES=1
