services:
  triton-server:
    container_name: triton-server
    image: nvcr.io/nvidia/tritonserver:24.06-py3
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: tritonserver --model-repository=/models --model-control-mode=explicit --load-model=*
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    volumes:
      - ../sam_models:/models
      - ../:/workspace/server
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NVIDIA_VISIBLE_DEVICES=1
    shm_size: "1gb"
    ulimits:
      memlock: -1
      stack: 67108864
    stdin_open: true
    tty: true
